name = "Modfest: Singularity"
author = "Modfest Organizers and Participants"
version = "0.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09eb9091b205b4d79e79eeefeebe47ee2b0a8807824a7c8589f8380470383e13"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
