name = "Modfest: Singularity"
author = "Modfest Organizers and Participants"
version = "0.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17f91113df3050146dbbd3afe323dda0c70a4c2acdaeb0b1e1d5c46141a96877"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
