name = "Modfest - Singularity"
author = "ModFest"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b7c4f2283af905bcbc02eb7dc49d4060d3c3a7b02e03897be244957b8114afa"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
