name = "Modfest - Singularity"
author = "ModFest"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7c514dc58c12067c646cd38faa6786b3bcf2aaee2056349a5f7f721c2eaac83"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
