name = "Modfest - Singularity"
author = "ModFest"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31fd6666db9b530c400cdf2708fc2f8b1d659a8767509dedcad78afacf249705"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
