name = "Modfest - Singularity"
author = "ModFest"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c94df8bb928970d47937dbb75fdeede6ed850f3d00095ee2968f27663687fc1"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"
